AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Studio

Metadata: &config
  Environment:
    - Name: DEPLOYMENT_ENV
      Value: !Ref DeploymentEnv
    - Name: DJANGO_SETTINGS_MODULE
      Value: !Sub 'server.settings.${Prefix}-${DeploymentEnv}'
    - Name: QUEUE_URL
      Value: !Ref Queue
  Secrets:
    - Name: DB_HOSTNAME
      ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DeploymentEnv}.studio.rds:host::'
    - Name: DB_USERNAME
      ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DeploymentEnv}.studio.rds:username::'
    - Name: DB_PASSWORD
      ValueFrom: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DeploymentEnv}.studio.rds:password::'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  DeploymentEnv:
    Type: String
  Prefix:
    Type: String
  Cluster:
    Type: String
  StudioImage:
    Type: String
  RDSSecurityGroup:
    Type: String
  PublicALBSecurityGroupId:
    Type: String
  PublicALBHTTPSListenerArn:
    Type: String
  PrivateALBSecurityGroupId:
    Type: String
  PrivateALBHTTPSListenerArn:
    Type: String
  ALBPriority:
    Type: Number
  ContainerPort:
    Type: Number
    Default: 8000
  StorageTopicARN:
    Type: String

Mappings:
  ServiceGroupSize:
    dev:
      Desired: 1
    stage:
      Desired: 1
    prod:
      Desired: 1

Resources:
  Queue:
    Type: AWS::SQS::Queue

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SNS
            Effect: Allow
            Principal: '*'
            Action:
              - sqs:SendMessage
            Resource: !GetAtt Queue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref StorageTopicARN
      Queues:
        - !Ref Queue

  TopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref StorageTopicARN
      Endpoint: !GetAtt Queue.Arn

  PublicALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ContainerPort
      HealthCheckEnabled: true
      HealthCheckPath: !Sub '/health/'
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      TargetGroupAttributes:
        - Key: 'deregistration_delay.timeout_seconds'
          Value: 60

  PrivateALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ContainerPort
      HealthCheckEnabled: true
      HealthCheckPath: !Sub '/health/'
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      TargetGroupAttributes:
        - Key: 'deregistration_delay.timeout_seconds'
          Value: 60

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: '2012-10-17'

  TaskRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: cloudformation:DescribeStacks
            Effect: Allow
            Resource: !Sub 'arn:aws:cloudformation:*:${AWS::AccountId}:stack/${Prefix}-${DeploymentEnv}-*'
          - Action: ssm:GetParameter
            Effect: Allow
            Resource: !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/${Prefix}-${DeploymentEnv}-*'
          - Action: lambda:InvokeFunction
            Effect: Allow
            Resource: !Sub 'arn:aws:lambda:*:${AWS::AccountId}:function:${Prefix}-${DeploymentEnv}-*'
          - Action: sns:Publish
            Effect: Allow
            Resource: !Sub 'arn:aws:sns:*:${AWS::AccountId}:${Prefix}-${DeploymentEnv}-*'
          - Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
            Effect: Allow
            Resource: !Sub 'arn:aws:sqs:*:${AWS::AccountId}:${Prefix}-${DeploymentEnv}-*'
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectAcl
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${Prefix}-${DeploymentEnv}-storage/*'
      PolicyName: !Sub '${AWS::StackName}-task-role-policy'
      Roles:
        - !Ref TaskRole

  TaskLogGroup:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Properties:
      RetentionInDays: 30

  MigrationTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      Family: !Sub '${AWS::StackName}-migration'
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: 512
      Memory: 1024
      ContainerDefinitions:
        - Name: 'migration'
          Image: !Ref StudioImage
          Command:
            - python
            - manage.py
            - migrate
            - --noinput
          <<: *config
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref TaskLogGroup
              awslogs-stream-prefix: ecs
              awslogs-create-group: true
    DependsOn:
      - TaskExecutionRolePolicy
      - TaskRolePolicy

  MigrationResourceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: '/'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: Lambda
            Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              Service:
                - lambda.amazonaws.com

  MigrationPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Ref AWS::StackName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'iam'
            Action:
              - 'iam:PassRole'
            Resource:
              - !GetAtt TaskRole.Arn
              - !GetAtt TaskExecutionRole.Arn
            Effect: Allow
          - Sid: 'ecs'
            Action:
              - 'ecs:ListTasks'
              - 'ecs:DescribeTasks'
              - 'ecs:RunTask'
            Resource: '*'
            Effect: Allow
          - Sid: 'crhelper'
            Action:
              - 'lambda:AddPermission'
              - 'lambda:RemovePermission'
              - 'events:PutRule'
              - 'events:DeleteRule'
              - 'events:PutTargets'
              - 'events:RemoveTargets'
            Resource: '*'
            Effect: Allow
      Roles:
        - !Ref MigrationResourceRole

  MigrationTaskLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 5
      Role: !GetAtt MigrationResourceRole.Arn
    Metadata:
      DockerContext: sam/migration/migrate
      Dockerfile: ./Dockerfile
      DockerTag: python3.9-v1
    DependsOn:
      - MigrationTask
      - MigrationPolicy

  MigrationTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${MigrationTaskLambda}'
      RetentionInDays: 1

  MigrationTaskResource:
    Type: Custom::Migration
    Properties:
      ServiceToken: !GetAtt MigrationTaskLambda.Arn
      Cluster: !Ref Cluster
      TaskDefinition: !Ref MigrationTask
      Family: !Sub '${AWS::StackName}-migration'
      Subnets: !Ref PrivateSubnets
      SecurityGroups:
        - !GetAtt ServiceSecurityGroup.GroupId
    DependsOn:
      - TaskRolePolicy
      - TaskExecutionRolePolicy

  MigrationPollerLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 5
      Role: !GetAtt MigrationResourceRole.Arn
    Metadata:
      DockerContext: sam/migration/poll
      Dockerfile: ./Dockerfile
      DockerTag: python3.9-v1
    DependsOn:
      - MigrationTask
      - MigrationPolicy
      - ServiceToRDSIngress

  MigrationPollerResource:
    Type: Custom::Migration
    Properties:
      ServiceToken: !GetAtt MigrationPollerLambda.Arn
      Cluster: !Ref Cluster
      TaskArn: !GetAtt MigrationTaskResource.TaskArn

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: '2012-10-17'

  TaskExecutionRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:BatchGetImage
              - ecr:GetDownloadUrlForLayer
            Effect: Allow
            Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${Prefix}'
          - Action: ecr:GetAuthorizationToken
            Effect: Allow
            Resource: '*'
          - Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: !GetAtt TaskLogGroup.Arn
          - Action:
              - secretsmanager:DescribeSecret
              - secretsmanager:GetSecretValue
            Effect: Allow
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DeploymentEnv}.studio.*'
        Version: '2012-10-17'
      PolicyName: !Sub '${AWS::StackName}-execution-role-policy'
      Roles:
        - !Ref TaskExecutionRole

  QueuePollerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: storage-queue-poller
          Essential: true
          Image: !Ref StudioImage
          <<: *config
          Command:
            - python
            - manage.py
            - poller_storage
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TaskLogGroup
              awslogs-stream-prefix: !Sub '${AWS::StackName}-storage-queue-poller'
              awslogs-region: !Ref AWS::Region
              awslogs-create-group: true
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      Family: !Sub '${AWS::StackName}-queue-poller'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !GetAtt TaskRole.Arn
    DependsOn:
      - TaskExecutionRolePolicy
      - TaskRolePolicy

  QueuePollerService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt ServiceSecurityGroup.GroupId
          Subnets: !Ref PrivateSubnets
      ServiceName: !Sub '${AWS::StackName}-queue-pollers'
      TaskDefinition: !Ref QueuePollerTaskDefinition
    DependsOn:
      - MigrationPollerResource

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Essential: true
          HealthCheck:
            Command:
              - CMD-SHELL
              - !Sub 'curl -f http://localhost:8000/health/ || exit 1'
            Interval: 10
            Retries: 2
            StartPeriod: 5
            Timeout: 5
          Image: !Ref StudioImage
          <<: *config
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref TaskLogGroup
              awslogs-stream-prefix: !Sub '${AWS::StackName}-service'
              awslogs-region: !Ref AWS::Region
              awslogs-create-group: true
          Name: studio
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp
      Cpu: 512
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      Family: !Sub '${AWS::StackName}-service-task-definition'
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      TaskRoleArn: !GetAtt TaskRole.Arn
    DependsOn:
      - TaskExecutionRolePolicy
      - TaskRolePolicy

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !FindInMap [ServiceGroupSize, !Ref DeploymentEnv, Desired]
      LoadBalancers:
        - ContainerName: studio
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref PublicALBTargetGroup
        - ContainerName: studio
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref PrivateALBTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !GetAtt ServiceSecurityGroup.GroupId
          Subnets: !Ref PrivateSubnets
      ServiceName: !Sub '${AWS::StackName}-service'
      TaskDefinition: !Ref TaskDefinition
      EnableECSManagedTags: true
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      HealthCheckGracePeriodSeconds: 5
      LaunchType: FARGATE
    DependsOn:
      - MigrationPollerResource
      - PublicALBTargetGroup
      - PublicALBRule1
      - PrivateALBTargetGroup
      - PrivateALBRule1

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Security group for ${AWS::StackName}-service'
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: '-1'
      VpcId: !Ref VpcId

  ServiceToRDSIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Allow access from Studio
      SourceSecurityGroupId: !GetAtt ServiceSecurityGroup.GroupId
      GroupId: !Ref RDSSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432

  PublicALBToServiceSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Public load balancer to Studio
      SourceSecurityGroupId: !Ref PublicALBSecurityGroupId
      GroupId: !GetAtt ServiceSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: !Ref ContainerPort
      ToPort: !Ref ContainerPort

  PublicALBToServiceSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: Public load balancer to Studio
      GroupId: !Ref PublicALBSecurityGroupId
      DestinationSecurityGroupId: !GetAtt ServiceSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: !Ref ContainerPort
      ToPort: !Ref ContainerPort

  StudioToPublicALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Studio to public load balancer
      GroupId: !Ref PublicALBSecurityGroupId
      SourceSecurityGroupId: !GetAtt ServiceSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443

  PublicALBRule1:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref PublicALBTargetGroup
          Type: forward
      Conditions:
        - Field: http-header
          HttpHeaderConfig:
            HttpHeaderName: !Sub 'x-${Prefix}-app'
            Values:
              - !Ref AWS::StackName
      ListenerArn: !Ref PublicALBHTTPSListenerArn
      Priority: !Ref ALBPriority

  PrivateALBToServiceSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Private load balancer to Studio
      SourceSecurityGroupId: !Ref PrivateALBSecurityGroupId
      GroupId: !GetAtt ServiceSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: !Ref ContainerPort
      ToPort: !Ref ContainerPort

  PrivateALBToServiceSecurityGroupEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      Description: Private load balancer to Studio
      GroupId: !Ref PrivateALBSecurityGroupId
      DestinationSecurityGroupId: !GetAtt ServiceSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: !Ref ContainerPort
      ToPort: !Ref ContainerPort

  StudioToPrivateALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Studio to Private load balancer
      GroupId: !Ref PrivateALBSecurityGroupId
      SourceSecurityGroupId: !GetAtt ServiceSecurityGroup.GroupId
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443

  PrivateALBRule1:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - TargetGroupArn: !Ref PrivateALBTargetGroup
          Type: forward
      Conditions:
        - Field: http-header
          HttpHeaderConfig:
            HttpHeaderName: !Sub 'x-${Prefix}-app'
            Values:
              - !Ref AWS::StackName
      ListenerArn: !Ref PrivateALBHTTPSListenerArn
      Priority: !Ref ALBPriority