version: 2.1

executors:
  default:
    docker:
      - image: cimg/python:3.10.8

orbs:
  docker: circleci/docker@2.5.0
  sam: circleci/aws-sam-serverless@6.1.0
  aws-cli: circleci/aws-cli@5.4.0

commands:
  fast_checkout:
    steps:
      - run:
          name: GitHub clone
          command: |
            mkdir ~/.ssh || true
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git clone "${CIRCLE_REPOSITORY_URL}" --branch "${CIRCLE_BRANCH}" --depth=1 .

  lint:
    steps:
      - run:
          name: Lint
          command: |
            pip install -r requirements.txt
            black -S app/studio --force-exclude migrations --line-length 90 --check

  test:
    steps:
      - run:
          name: Test
          command: |
            # TODO figure out a way to use the container
            DJANGO_SETTINGS_MODULE=server.settings.e2e-local python app/manage.py test studio

  sam_build_deploy:
    parameters:
      stack_name:
        type: string
      environment:
        type: string
      overrides:
        type: string
      tags:
        type: string
      template:
        type: string
        default: template.yml
    steps:
      - run:
          name: SAM Build
          command: |
            sam build \
              --template-file <<parameters.template>> \
              --parameter-overrides "<<parameters.overrides>>" \
              --parallel \
              --config-file e2esamconfig.toml
      - run:
          name: SAM Deploy
          no_output_timeout: 30m
          command: |
            sam deploy \
              --stack-name <<parameters.stack_name>> \
              --parameter-overrides "<<parameters.overrides>>" \
              --image-repository "052457202381.dkr.ecr.us-west-2.amazonaws.com/e2e" \
              --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-28m720vdnyft \
              --s3-prefix e2e_<<parameters.environment>>_studio \
              --capabilities CAPABILITY_IAM \
              --no-confirm-changeset \
              --no-fail-on-empty-changeset \
              --tags "<<parameters.tags>>" \
              --config-file e2esamconfig.toml

jobs:
  lint-test:
    steps:
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
      - fast_checkout
      - lint
      - test
    executor: default
    resource_class: large

  build-deploy:
    parameters:
      environment:
        type: string
      image_host:
        type: string
        default: 052457202381.dkr.ecr.us-west-2.amazonaws.com
      image_name:
        type: string
        default: e2e-studio
      alb_priority:
        type: integer
      storage_topic_arn:
        type: string
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - aws-cli/setup:
          role_arn: ${AWS_ROLE_ARN}
      - sam/install
      - fast_checkout
      - run:
          name: ECR Login
          command: |
            ECR_NAME=e2e
            ECR_HOST=052457202381.dkr.ecr.us-west-2.amazonaws.com
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${ECR_HOST}
            ECR_PATH=${ECR_HOST}/${ECR_NAME}
            
            echo "export ECR_NAME=${ECR_NAME}" >> ${BASH_ENV}
            echo "export ECR_PATH=${ECR_PATH}" >> ${BASH_ENV}
      - run:
          name: Image build
          command: |
            GIT_SHA=${CIRCLE_SHA1}
            APP_IMAGE_PATH=${ECR_PATH}:${GIT_SHA}
            docker build -f Dockerfile -t "${APP_IMAGE_PATH}" .
            docker push "${APP_IMAGE_PATH}"
            
            echo "export APP_IMAGE_PATH=${APP_IMAGE_PATH}" >> ${BASH_ENV}
      - run:
          name: Check migrations
          command: |
            docker run ${APP_IMAGE_PATH} python manage.py makemigrations
            docker run ${APP_IMAGE_PATH} python manage.py showmigrations
      - run:
          name: Lookup the RDS SecurityGroup
          command: |
            RDS_SG=$(aws cloudformation describe-stacks --stack-name=e2e-<<parameters.environment>>-studio-db --query="Stacks[0].Outputs[?OutputKey=='SecurityGroup'].OutputValue" --output text)
            echo "Found RDS Security Group: ${RDS_SG}"
            echo "export RDS_SG=${RDS_SG}" >> ${BASH_ENV}
      - sam_build_deploy:
          stack_name: e2e-<<parameters.environment>>-studio
          environment: <<parameters.environment>>
          overrides: >-
            StudioImage=${APP_IMAGE_PATH}
            DeploymentEnv=<<parameters.environment>>
            Prefix=e2e
            Settings=e2e-<<parameters.environment>>
            Cluster=e2e-prod-core
            PublicALBSecurityGroupId=sg-0989ce36f62da2ae7
            PublicALBHTTPSListenerArn=arn:aws:elasticloadbalancing:us-west-2:052457202381:listener/app/e2e-prod-core-public/fb3b6a1bd7e27679/9ab155a6201d87e0
            PublicALBDNSRecord=e2e-prod-core-public-alb.modsy.com
            PrivateALBSecurityGroupId=sg-06fcee45cb5fc51b7
            PrivateALBHTTPSListenerArn=arn:aws:elasticloadbalancing:us-west-2:052457202381:listener/app/e2e-prod-core-private/1c7ba88c97adf469/cd7e4004ffc156d6
            PrivateALBDNSRecord=e2e-prod-core-private-alb.private.modsy.com
            RDSSecurityGroup=${RDS_SG}
            VpcId=vpc-0df37fa28593dad4e
            PrivateSubnets=subnet-0bc5a566f52ea1e09,subnet-0aa84d4f12dbfb323
            ALBPriority=<<parameters.alb_priority>>
            StorageTopicARN=<<parameters.storage_topic_arn>>
          tags: >-
            org=e2e
            app=studio
            env=<<parameters.environment>>
            ApplicationName=\"Studio BE\"
            ApplicationID=ID045611
            ApplicationOwner=\"Adam Konrad\"
            CostCenter=\"1901901 - 3d Tools\"
            Environment=<<parameters.environment>>
            Budget=100000
    executor: default
    resource_class: small

workflows:
  studio:
    jobs:
      - lint-test:
          context: aws
          filters:
            branches:
              ignore:
                - main
      - build-deploy:
          context: aws
          environment: 'dev'
          storage_topic_arn: 'arn:aws:sns:us-west-2:052457202381:e2e-dev-storage-Topic-9QSPbYMurh6P'
          alb_priority: 352
          filters:
            branches:
              only: main
