"""
Django settings for django project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
import boto3

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

DEBUG = False
DEPLOYMENT_ENV = os.getenv('DEPLOYMENT_ENV', 'dev')

BASE_DIR = Path(__file__).resolve().parent.parent.parent
SECRET_KEY = 'django-insecure-3rcbe+gz$rym9f23&)7l-7^sr55c5pw=h567prfpeks_*n3^5*'
ALLOWED_HOSTS = ['*']
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django_filters',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'rest_framework',
    'studio',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
]
ROOT_URLCONF = 'server.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]
WSGI_APPLICATION = 'server.wsgi.application'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {'timeout': 60},
    }
}
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'UNAUTHENTICATED_USER': None,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SPECTACULAR_SETTINGS = {
    'TITLE': 'Studio API',
    'DESCRIPTION': 'API documentation for Studio back-end',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Local Development server'},
        {'url': 'https://dev.modsy.com', 'description': 'Development server'},
        {'url': 'https://staging.modsy.com', 'description': 'Staging server'},
        {'url': 'https://modsy.com', 'description': 'Production server'},
    ],
}

sentry_sdk.init(
    environment=DEPLOYMENT_ENV,
    dsn="https://36d901f6c0d66f845e2cf9fd9eea9843@sentry.modsy.com/21",
    integrations=[
        DjangoIntegration(),
    ],
    traces_sample_rate=1.0,
    send_default_pii=True,
)

QUEUE_URL = os.getenv('QUEUE_URL')

AWS_REGION = 'us-west-2'

AWS_CLIENT_S3 = boto3.client('s3', region_name=AWS_REGION)
AWS_CLIENT_SQS = boto3.client('sqs', region_name=AWS_REGION)
AWS_CLIENT_CFN = boto3.client('cloudformation', region_name=AWS_REGION)
AWS_CLIENT_LAMBDA = boto3.client('lambda', region_name=AWS_REGION)

AWS_STACKS = []
