# Generated by Django 4.2.20 on 2025-05-14 00:21

from django.db import migrations, models
import django.db.models.deletion
import studio.models.element
import studio.models.file_status


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('version', models.CharField(max_length=128)),
                ('schema_data', models.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(default='')),
                (
                    'category',
                    models.IntegerField(
                        default=studio.models.element.ElementCategory[
                            'ElementCategoryNone'
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ElementData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('version', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ElementDataChange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.IntegerField()),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.IntegerField()),
                (
                    's3_prefix',
                    models.CharField(db_index=True, max_length=1024, null=True),
                ),
                ('s3_key', models.CharField(db_index=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileNotification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('file_id', models.BigIntegerField()),
                (
                    'status',
                    models.IntegerField(
                        default=studio.models.file_status.FileStatus['Created']
                    ),
                ),
                ('s3_key', models.CharField(db_index=True, max_length=1024)),
                ('s3_size', models.IntegerField()),
                ('s3_etag', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.JSONField()),
                ('version', models.CharField(max_length=128)),
                ('success', models.BooleanField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileOwnership',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'element_data',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='studio.elementdata',
                    ),
                ),
                (
                    'file',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name='ownership',
                        to='studio.file',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['type'], name='studio_file_type_2ed07d_idx'),
        ),
        migrations.AddField(
            model_name='elementdatachange',
            name='element_data',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='studio.elementdata'
            ),
        ),
        migrations.AddField(
            model_name='elementdata',
            name='element',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to='studio.element'
            ),
        ),
    ]
