# Generated by Django 4.2.20 on 2025-05-20 13:54

from django.db import migrations, models
import django.db.models.deletion
import studio.models.room


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.TextField(default='')),
                (
                    'category',
                    models.IntegerField(
                        default=studio.models.room.RoomCategory['RoomCategoryNone']
                    ),
                ),
                ('function', models.TextField(default='')),
                ('type', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RoomData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('version', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to='studio.room'
                    ),
                ),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='RoomElement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                (
                    'element_data',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='studio.elementdata',
                    ),
                ),
                (
                    'room_data',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to='studio.roomdata',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RoomDataChange',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('type', models.IntegerField()),
                ('description', models.TextField(default='')),
                (
                    'room_data',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to='studio.roomdata'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='fileownership',
            name='room_data',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='studio.roomdata',
            ),
        ),
        migrations.AddField(
            model_name='fileownership',
            name='room_element',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='studio.roomelement',
            ),
        ),
    ]
