# Generated by Django 4.2.20 on 2025-06-09 16:42

from django.db import migrations, models
import studio.models.element


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_room_roomdata_roomelement_roomdatachange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='category',
            field=models.TextField(
                default=studio.models.element.ElementCategory['ElementCategoryNone']
            ),
        ),
    ]
