# Generated by Django 4.2.20 on 2025-06-09 17:18

from django.db import migrations, models
import studio.models.room


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_element_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.TextField(
                default=studio.models.room.RoomCategory['RoomCategoryNone']
            ),
        ),
    ]
