# Generated by Django 4.2.20 on 2025-06-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_alter_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
