# Generated by Django 4.2.20 on 2025-06-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_elementdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
