# Generated by Django 4.2.20 on 2025-07-16 15:34

from django.db import migrations, models
import studio.models.file_status


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_roomelement_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdata',
            name='required_file_count',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='roomdata',
            name='required_file_count',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='elementdata',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='filenotification',
            name='file_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='filenotification',
            name='status',
            field=models.IntegerField(
                db_index=True, default=studio.models.file_status.FileStatus['Created']
            ),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
