# Generated by Django 4.2.20 on 2025-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_elementdata_required_file_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdata',
            name='current_file_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='roomdata',
            name='current_file_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='elementdata',
            name='required_file_count',
            field=models.IntegerField(db_index=True, default=4),
        ),
        migrations.AlterField(
            model_name='roomdata',
            name='required_file_count',
            field=models.IntegerField(db_index=True, default=2),
        ),
        migrations.AddIndex(
            model_name='elementdata',
            index=models.Index(
                fields=['deleted_at', 'current_file_count', 'required_file_count'],
                name='studio_elem_deleted_3ea090_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='roomdata',
            index=models.Index(
                fields=['deleted_at', 'current_file_count', 'required_file_count'],
                name='studio_room_deleted_3a6771_idx',
            ),
        ),
    ]
