# Generated by Django 4.2.23 on 2025-08-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_current_file_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementdatachange',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementdatachange',
            name='previous_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementdatachange',
            name='property',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdatachange',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdatachange',
            name='previous_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomdatachange',
            name='property',
            field=models.TextField(blank=True, null=True),
        ),
    ]
