name: Stage Studio CI/CD

on:
  push:
    branches:
      - stage
      - stage-clean
  pull_request:
    branches:
      - stage

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
  ECR_REPOSITORY: veev
  ECR_HOST: 505794203161.dkr.ecr.us-east-1.amazonaws.com

jobs:
  undeploy-app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: github.ref == 'refs/heads/stage-clean'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Undeploy stage
        run: |
          aws cloudformation delete-stack --stack-name=veev-stage-studio
          aws cloudformation wait stack-delete-complete --stack-name=veev-stage-studio

  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: [undeploy-app]
    if: |
      github.ref == 'refs/heads/stage-clean'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set environment variables
        id: set-env
        run: |
          echo "ENVIRONMENT=stage" >> $GITHUB_ENV
          echo "CLUSTER=veev-stage-core" >> $GITHUB_ENV
          echo "VPC_ID=vpc-0a6d03d7e95ed4751" >> $GITHUB_ENV
          echo "PRIVATE_SUBNETS=subnet-0757a35c00aa418ea,subnet-0ba3ee09261250f52" >> $GITHUB_ENV
          echo "PUBLIC_ALB_SG=sg-0576c41f0fd1e2169" >> $GITHUB_ENV
          echo "PUBLIC_ALB_LISTENER=arn:aws:elasticloadbalancing:us-east-1:505794203161:listener/app/veev-stage-core-public/278ec71a5cbfcac3/3cb1926030b263af" >> $GITHUB_ENV
          echo "PUBLIC_ALB_DNS=veev-stage-core.veev.com" >> $GITHUB_ENV
          echo "PRIVATE_ALB_SG=sg-0ba0a5b890cde01b6" >> $GITHUB_ENV
          echo "PRIVATE_ALB_LISTENER=arn:aws:elasticloadbalancing:us-east-1:505794203161:listener/app/veev-stage-core-private/7b8527288ac7d283/48181205b6a5f6bf" >> $GITHUB_ENV
          echo "ALB_PRIORITY=351" >> $GITHUB_ENV
          echo "STORAGE_TOPIC_ARN=arn:aws:sns:us-east-1:505794203161:veev-stage-storage-Topic-5km41CuiAen3" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Check migrations
        run: |
          docker run ${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} python manage.py makemigrations
          docker run ${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} python manage.py showmigrations

      - name: Lookup RDS SecurityGroup
        run: |
          RDS_SG=$(aws cloudformation describe-stacks --stack-name=veev-${{ env.ENVIRONMENT }}-studio-db --query="Stacks[0].Outputs[?OutputKey=='SecurityGroup'].OutputValue" --output text)
          echo "Found RDS Security Group: ${RDS_SG}"
          echo "RDS_SG=${RDS_SG}" >> $GITHUB_ENV

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM Build
        run: |
          sam build \
            --template-file template.yml \
            --parameter-overrides "StudioImage=${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} DeploymentEnv=${{ env.ENVIRONMENT }} Prefix=veev Settings=${{ env.ENVIRONMENT }} Cluster=${{ env.CLUSTER }} PublicALBSecurityGroupId=${{ env.PUBLIC_ALB_SG }} PublicALBHTTPSListenerArn=${{ env.PUBLIC_ALB_LISTENER }} PublicALBDNSRecord=${{ env.PUBLIC_ALB_DNS }} PrivateALBSecurityGroupId=${{ env.PRIVATE_ALB_SG }} PrivateALBHTTPSListenerArn=${{ env.PRIVATE_ALB_LISTENER }} RDSSecurityGroup=${RDS_SG} VpcId=${{ env.VPC_ID }} PrivateSubnets=${{ env.PRIVATE_SUBNETS }} ALBPriority=${{ env.ALB_PRIORITY }} StorageTopicARN=${{ env.STORAGE_TOPIC_ARN }}" \
            --config-file veevsamconfig.toml \
            --config-env ${{ env.ENVIRONMENT }} \
            --parallel

      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name veev-${{ env.ENVIRONMENT }}-studio \
            --parameter-overrides "StudioImage=${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} DeploymentEnv=${{ env.ENVIRONMENT }} Prefix=veev Settings=${{ env.ENVIRONMENT }} Cluster=${{ env.CLUSTER }} PublicALBSecurityGroupId=${{ env.PUBLIC_ALB_SG }} PublicALBHTTPSListenerArn=${{ env.PUBLIC_ALB_LISTENER }} PublicALBDNSRecord=${{ env.PUBLIC_ALB_DNS }} PrivateALBSecurityGroupId=${{ env.PRIVATE_ALB_SG }} PrivateALBHTTPSListenerArn=${{ env.PRIVATE_ALB_LISTENER }} RDSSecurityGroup=${RDS_SG} VpcId=${{ env.VPC_ID }} PrivateSubnets=${{ env.PRIVATE_SUBNETS }} ALBPriority=${{ env.ALB_PRIORITY }} StorageTopicARN=${{ env.STORAGE_TOPIC_ARN }}" \
            --image-repository "${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}" \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --tags "org=veev app=studio env=${{ env.ENVIRONMENT }} ApplicationName=\"Studio BE\" ApplicationOwner=\"Adam Konrad\" Environment=${{ env.ENVIRONMENT }}" \
            --config-file veevsamconfig.toml \
            --config-env ${{ env.ENVIRONMENT }}

  build-deploy-direct:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    if: |
      github.ref == 'refs/heads/stage'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set environment variables
        id: set-env
        run: |
          echo "ENVIRONMENT=stage" >> $GITHUB_ENV
          echo "CLUSTER=veev-stage-core" >> $GITHUB_ENV
          echo "VPC_ID=vpc-0a6d03d7e95ed4751" >> $GITHUB_ENV
          echo "PRIVATE_SUBNETS=subnet-0757a35c00aa418ea,subnet-0ba3ee09261250f52" >> $GITHUB_ENV
          echo "PUBLIC_ALB_SG=sg-0576c41f0fd1e2169" >> $GITHUB_ENV
          echo "PUBLIC_ALB_LISTENER=arn:aws:elasticloadbalancing:us-east-1:505794203161:listener/app/veev-stage-core-public/278ec71a5cbfcac3/3cb1926030b263af" >> $GITHUB_ENV
          echo "PUBLIC_ALB_DNS=veev-stage-core.veev.com" >> $GITHUB_ENV
          echo "PRIVATE_ALB_SG=sg-0ba0a5b890cde01b6" >> $GITHUB_ENV
          echo "PRIVATE_ALB_LISTENER=arn:aws:elasticloadbalancing:us-east-1:505794203161:listener/app/veev-stage-core-private/7b8527288ac7d283/48181205b6a5f6bf" >> $GITHUB_ENV
          echo "ALB_PRIORITY=351" >> $GITHUB_ENV
          echo "STORAGE_TOPIC_ARN=arn:aws:sns:us-east-1:505794203161:veev-stage-storage-Topic-5km41CuiAen3" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Check migrations
        run: |
          docker run ${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} python manage.py makemigrations
          docker run ${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} python manage.py showmigrations

      - name: Lookup RDS SecurityGroup
        run: |
          RDS_SG=$(aws cloudformation describe-stacks --stack-name=veev-${{ env.ENVIRONMENT }}-studio-db --query="Stacks[0].Outputs[?OutputKey=='SecurityGroup'].OutputValue" --output text)
          echo "Found RDS Security Group: ${RDS_SG}"
          echo "RDS_SG=${RDS_SG}" >> $GITHUB_ENV

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: SAM Build
        run: |
          sam build \
            --template-file template.yml \
            --parameter-overrides "StudioImage=${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} DeploymentEnv=${{ env.ENVIRONMENT }} Prefix=veev Settings=${{ env.ENVIRONMENT }} Cluster=${{ env.CLUSTER }} PublicALBSecurityGroupId=${{ env.PUBLIC_ALB_SG }} PublicALBHTTPSListenerArn=${{ env.PUBLIC_ALB_LISTENER }} PrivateALBSecurityGroupId=${{ env.PRIVATE_ALB_SG }} PrivateALBHTTPSListenerArn=${{ env.PRIVATE_ALB_LISTENER }} RDSSecurityGroup=${RDS_SG} VpcId=${{ env.VPC_ID }} PrivateSubnets=${{ env.PRIVATE_SUBNETS }} ALBPriority=${{ env.ALB_PRIORITY }} StorageTopicARN=${{ env.STORAGE_TOPIC_ARN }}" \
            --config-file veevsamconfig.toml \
            --config-env ${{ env.ENVIRONMENT }} \
            --parallel

      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name veev-${{ env.ENVIRONMENT }}-studio \
            --parameter-overrides "StudioImage=${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} DeploymentEnv=${{ env.ENVIRONMENT }} Prefix=veev Settings=${{ env.ENVIRONMENT }} Cluster=${{ env.CLUSTER }} PublicALBSecurityGroupId=${{ env.PUBLIC_ALB_SG }} PublicALBHTTPSListenerArn=${{ env.PUBLIC_ALB_LISTENER }} PrivateALBSecurityGroupId=${{ env.PRIVATE_ALB_SG }} PrivateALBHTTPSListenerArn=${{ env.PRIVATE_ALB_LISTENER }} RDSSecurityGroup=${RDS_SG} VpcId=${{ env.VPC_ID }} PrivateSubnets=${{ env.PRIVATE_SUBNETS }} ALBPriority=${{ env.ALB_PRIORITY }} StorageTopicARN=${{ env.STORAGE_TOPIC_ARN }}" \
            --image-repository "${{ env.ECR_HOST }}/${{ env.ECR_REPOSITORY }}" \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --tags "org=veev app=studio env=${{ env.ENVIRONMENT }} ApplicationName=\"Studio BE\" ApplicationOwner=\"Adam Konrad\" Environment=${{ env.ENVIRONMENT }}" \
            --config-file veevsamconfig.toml \
            --config-env ${{ env.ENVIRONMENT }}
